# Generated by Django 6.1.1 on 2026-09-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=150)),
                ('brief', models.TextField()),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('warmup', 'Warmup'), ('core', 'Core'), ('boss_level', 'Boss Level')], max_length=20)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('in_progress', 'In Progress'), ('cracked', 'Cracked'), ('expired', 'Expired')], default='unclaimed', max_length=20)),
                ('hostel', models.CharField(choices=[('Ashok Bhawan', 'Ashok Bhawan'), ('Bhagirath Bhawan', 'Bhagirath Bhawan'), ('Budh Bhawan', 'Budh Bhawan'), ('C.V. Raman Bhawan', 'C.V. Raman Bhawan'), ('Gandhi Bhawan', 'Gandhi Bhawan'), ('Krishna Bhawan', 'Krishna Bhawan'), ('Malaviya Bhawan-A', 'Malaviya Bhawan-A'), ('Malaviya Bhawan-B', 'Malaviya Bhawan-B'), ('Malaviya Bhawan-C', 'Malaviya Bhawan-C'), ('Malaviya Apartments', 'Malaviya Apartments'), ('Rana Pratap Bhawan', 'Rana Pratap Bhawan'), ('Ram Bhawan', 'Ram Bhawan'), ('Shankar Bhawan', 'Shankar Bhawan'), ('Srinivasa Ramanujan (SR) Bhawan', 'Srinivasa Ramanujan (SR) Bhawan'), ('Vishwakarma Bhawan', 'Vishwakarma Bhawan'), ('Vyas Bhawan', 'Vyas Bhawan'), ('Meera Bhawan', 'Meera Bhawan')], max_length=50)),
                ('solver_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
